const clock=document.getElementById('clock'),date=document.getElementById('date'),year=document.getElementById('year');
function updateTime(){const now=new Date();clock.textContent=now.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});date.textContent=now.toLocaleDateString([],{weekday:'short',day:'numeric',month:'short'});if(year)year.textContent=now.getFullYear()}updateTime();setInterval(updateTime,1000);
const stars=document.getElementById('stars');if(stars){for(let i=0;i<Math.min(55,Math.floor(innerWidth/20));i++){const s=document.createElement('i');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*4+'s';s.style.animationDuration=3+Math.random()*4+'s';stars.appendChild(s)}}
const searchForm=document.getElementById('searchForm'),searchInput=document.getElementById('searchInput');function goSearch(){const q=searchInput.value.trim();if(!q)return;const url=/^(https?:\/\/|www\.)|\.[a-z]{2,}(\/|$)/i.test(q)?(q.startsWith('http')?q:'https://'+q):'https://www.google.com/search?q='+encodeURIComponent(q);location.href=url}searchForm.addEventListener('submit',e=>{e.preventDefault();goSearch()});document.getElementById('focusSearch').addEventListener('click',()=>{searchInput.focus();searchInput.select()});
const panel=document.getElementById('aiPanel'),launcher=document.getElementById('aiLauncher'),close=document.getElementById('aiClose'),chatInput=document.getElementById('chatInput'),readyModal=document.getElementById('readyModal'),readyButton=document.getElementById('readyButton'),cancelReady=document.getElementById('cancelReady'),transition=document.getElementById('aiTransition');let aiInitialized=false,opening=false,readyMode=false;
launcher.addEventListener('click',()=>{if(opening)return;if(!aiInitialized&&!readyMode)startAISequence();else if(readyMode)showReady();else openAI()});
cancelReady.addEventListener('click',()=>{readyModal.classList.remove('show');readyModal.setAttribute('aria-hidden','true');readyMode=false});
readyButton.addEventListener('click',()=>{readyModal.classList.remove('show');readyModal.setAttribute('aria-hidden','true');readyMode=false;openAI()});
function startAISequence(){opening=true;readyMode=false;transition.classList.add('show');transition.setAttribute('aria-hidden','false');const labels=['LOADING AI','INITIALIZING CORE','CALIBRATING NEURAL INTERFACE','SYNCING NOVA SYSTEMS','FINALIZING AI'];let i=0;const label=transition.querySelector('.transition-label');label.textContent=labels[0];const cycle=setInterval(()=>{i=(i+1)%labels.length;label.textContent=labels[i]},650);setTimeout(()=>{clearInterval(cycle);opening=false;readyMode=true;transition.classList.remove('show');transition.setAttribute('aria-hidden','true');showReady()},4000)}
function showReady(){readyModal.classList.add('show');readyModal.setAttribute('aria-hidden','false');setTimeout(()=>readyButton.focus(),50)}
function openAI(){if(opening)return;opening=true;transition.classList.add('show');transition.setAttribute('aria-hidden','false');transition.querySelector('.transition-label').textContent='CONNECTING TO NOVA AI';setTimeout(()=>{transition.classList.add('launching');setTimeout(()=>{transition.classList.remove('show','launching');transition.setAttribute('aria-hidden','true');panel.classList.add('open');aiInitialized=true;opening=false;chatInput.focus()},850)},1100)}
close.addEventListener('click',()=>panel.classList.remove('open'));
const chatForm=document.getElementById('chatForm'),messages=document.getElementById('messages');chatForm.addEventListener('submit',e=>{e.preventDefault();const text=chatInput.value.trim();if(!text)return;addMessage(text,'user');chatInput.value='';setTimeout(()=>addMessage(getDemoReply(text),'bot'),350)});function addMessage(text,type){const el=document.createElement('div');el.className='message '+type;el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight}function getDemoReply(text){const q=text.toLowerCase();if(q.includes('hello')||q.includes('hi'))return'Hello. NOVA AI is currently running in demo mode.';if(q.includes('time'))return'The current time is '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+'.';if(q.includes('google'))return'Use the main search bar to search Google instantly.';return'I am only a local demo right now. Connect an AI backend later to enable real AI responses.'}
document.addEventListener('keydown',e=>{if(readyMode&&readyModal.classList.contains('show')&&(e.key==='Enter'||e.key===' ')){e.preventDefault();readyButton.click();return}if(e.key==='/'&&document.activeElement!==searchInput&&document.activeElement!==chatInput){e.preventDefault();searchInput.focus()}if(e.key==='Escape'){readyModal.classList.remove('show');readyModal.setAttribute('aria-hidden','true');transition.classList.remove('show');transition.setAttribute('aria-hidden','true');panel.classList.remove('open');opening=false;readyMode=false}});
const boot=document.getElementById('bootScreen'),progress=document.getElementById('bootProgress'),percent=document.getElementById('bootPercent'),bootText=document.getElementById('bootText');let start;const bootSteps=[[12,'INITIALIZING NOVA'],[28,'LOADING CORE SYSTEM'],[46,'CALIBRATING INTERFACE'],[67,'LOADING AI MODULE'],[84,'SYNCING WORKSPACE'],[100,'SYSTEM READY']];function bootLoop(now){const p=Math.min(100,(now-start)/4000*100);progress.style.width=p+'%';percent.textContent=Math.floor(p)+'%';let step=bootSteps[0];for(const item of bootSteps)if(p>=item[0])step=item;bootText.textContent=step[1];if(p<100)requestAnimationFrame(bootLoop);else setTimeout(()=>boot.classList.add('hide'),500)}window.addEventListener('load',()=>{start=performance.now();requestAnimationFrame(bootLoop)});